// components/users/data.ts
import { User } from './column'

export const userData: User[] = [
  {
    name: 'Lindsey Stroud',
    email: 'lindsey.stroud@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/lindsey.png',
  },
  {
    name: 'Nicci Troiani',
    email: 'nicci.troiani@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/nicci.png',
  },
  {
    name: 'George Fields',
    email: 'george.fields@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/george.png',
  },
  {
    name: 'Rebecca Moore',
    email: 'rebecca.moore@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/rebecca.png',
  },
  {
    name: 'Jane Doe',
    email: 'jane.doe@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/jane.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
  {
    name: 'Franz Ferdinand',
    email: 'franz.ferdinand@gmail.com',
    phone: '+234 905 678 9900',
    business: 'Registered',
    industry: 'Finance',
    registered: 'Dec 14, 2018',
    avatar: '/avatars/franz.png',
  },
]
