export const auditData = [
  {
    datetime: '10/09/2021, 9:30AM',
    customer: 'Oluwatobi Immanuel - 112349IHG',
    email: 'immanuel.oluwatobi@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 9:35AM',
    customer: 'Adebayo Kolade - 118442KPT',
    email: 'adebayo.kolade@gmail.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 9:40AM',
    customer: 'Chinyere Okafor - 122198CHK',
    email: 'chinyere.okafor@yahoo.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 9:45AM',
    customer: 'Mustapha Bello - 119993MFB',
    email: 'mustapha.bello@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 9:50AM',
    customer: 'Grace Ibe - 113556GIC',
    email: 'grace.ibe@outlook.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 9:55AM',
    customer: 'John Uche - 117211JUC',
    email: 'john.uche@gmail.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:00AM',
    customer: 'Toyin Akinola - 123789TOY',
    email: 'toyakinola@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:05AM',
    customer: 'Yusuf Lawal - 118888YSL',
    email: 'lawalyusuf@gmail.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:10AM',
    customer: 'Fatima Abubakar - 114477FAB',
    email: 'fatima.abubakar@hotmail.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:15AM',
    customer: 'Ifeanyi Nwosu - 111233IFN',
    email: 'ifeanyi.nwosu@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:20AM',
    customer: 'Bolanle Oseni - 116722BOS',
    email: 'bolanle.oseni@gmail.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:25AM',
    customer: 'Abdulrahman Sulaiman - 123002ABD',
    email: 'abdulrahman.sulaiman@gmail.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:30AM',
    customer: 'Ngozi Eze - 119921NGZ',
    email: 'ngozi.eze@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:35AM',
    customer: 'Kenneth Iroha - 118182KEN',
    email: 'kenneth.iroha@yahoo.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:40AM',
    customer: 'Halima Mohammed - 122334HLM',
    email: 'halima.mohammed@gmail.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:45AM',
    customer: 'Samuel Akinyemi - 115543SAM',
    email: 'samuel.akinyemi@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:50AM',
    customer: 'Chioma Nwachukwu - 111455CHN',
    email: 'chioma.nwachukwu@gmail.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 10:55AM',
    customer: 'Tajudeen Ajayi - 120909TAJ',
    email: 'tajudeen.ajayi@outlook.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 11:00AM',
    customer: 'Kemi Balogun - 117799KEM',
    email: 'kemi.balogun@gmail.com',
    plan: 'PRO',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 11:05AM',
    customer: 'Abdulahi Isa - 112589ABD',
    email: 'abdulahi.isa@gmail.com',
    plan: 'BASIC',
    description: 'Added 5 members to account and activated all',
  },
  {
    datetime: '10/09/2021, 11:10AM',
    customer: 'Rita Nnamdi - 119845RIT',
    email: 'rita.nnamdi@yahoo.com',
    plan: 'FREE',
    description: 'Added 5 members to account and activated all',
  },
]
